version: '3.8'

services:
  portracker:
    image: portracker:latest
    container_name: portracker
    restart: unless-stopped
    network_mode: "host"
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/middleware/middlewared.sock:/var/run/middlewared.sock:ro  # For TrueNAS
      - ./portracker-data:/data
    
    environment:
      # CORE CONFIGURATION
      - DATABASE_PATH=/data/portracker.db
      - PORT=4999
      
      # TRUENAS INTEGRATION (Optional)
      - TRUENAS_API_KEY=your-api-key-here
      
      # PERFORMANCE SETTINGS
      - CACHE_TIMEOUT_MS=60000          # Cache duration (60 seconds)
      - DISABLE_CACHE=false             # Set to 'true' to disable caching
      - INCLUDE_UDP=false               # Set to 'true' to include UDP ports
      
      # DEBUGGING
      - DEBUG=false                     # Set to 'true' for verbose logging
      
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4999/api/health"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3